### ISSUE TITLE
Dash_User_Guide_and_Documentation.pdf loading problem

### ISSUE THREAD

**Issue by ptoulino** [plotly/dash-docs#958] opened 2020-09-05 09:36 UTC
**Please note:** When loading/downloading the pdf documentation I get nothing but blank documentation

This can be found in: 
*dash-docs/pdf-docs/Dash_User_Guide_and_Documentation.pdf*

<img width="794" alt="Screen Shot 2020-09-05 at 2 34 04 AM" src="https://user-images.githubusercontent.com/68033681/92302336-4c850780-ef20-11ea-8965-5770fc31f538.png">

**Comment by alexcjohnson** [comment] 2020-09-06 13:48
duplicate of #897

**Closed by alexcjohnson** 2020-09-06 13:48 UTC
