### ISSUE TITLE
add GTM to dash R docs and create GA view for it

### ISSUE THREAD

**Issue by VeraZab** [plotly/dash-docs#945] opened 2020-04-24 16:01 UTC
discovered as part of: https://github.com/plotly/marketing-team/issues/288

**Comment by HammadTheOne** [comment] 2020-09-12 02:30
I've opened a PR https://github.com/plotly/dash-docs/pull/962 which adds the GTM tags to the Dash R docs main app head and body by way of `index_string` as we did earlier with a couple of the Dash for R gallery apps. This should propagate to the individual chapters and pages within the docs. If we can validate that it's working as intended, I think it's safe to merge and close the issue.

**Comment by VeraZab** [comment] 2020-10-26 23:44
Actually, sorry, I had to check this a while ago and forgot.
I don't see the GTM on the dash r docs, were the changes deployed? I assume that yes as this PR was made a while ago?
If you open and inspect the live page of dashr docs, you'll see that the GTM scripts are not present.

**Comment by HammadTheOne** [comment] 2020-10-27 00:03
I don't believe we have redeployed the docs yet. We should have a chance to do so either later this week or next week once the PMC for R chapter is in along with some bugfixes and dockerfile updates.

**Comment by VeraZab** [comment] 2020-10-27 15:28
I would like to only close this issue when we're able to see the tag working on the live site, please update me once we've deployed.

**Comment by HammadTheOne** [comment] 2021-02-28 00:48
Dash R docs redeployed and GTM tags are live on site. Closing this issue.

**Closed by HammadTheOne** 2021-02-28 00:48 UTC
Labels: bug, size: 0.2
