### ISSUE TITLE
Add an example of table virtualization

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-docs#299] opened 2018-12-04 19:29 UTC

**Comment by chriddyp** [comment] 2018-12-04 23:01
@Marc-Andre-Rivet - could you fill this in a little bit with the properties or syntax? that'll make it easier for other folks to fill out the examples.

**Comment by chriddyp** [comment] 2018-12-04 23:01
alternatively, link to a integration test if one exists?

**Comment by michaelbabyn** [comment] 2018-12-20 19:02
duplicate of #339. This will be resolved by #341

**Closed by michaelbabyn** 2018-12-20 19:02 UTC
