### ISSUE TITLE
Empty/Whiteout userguide

### ISSUE THREAD

**Issue by DrakezulsMinimalism** [plotly/dash-docs#971] opened 2020-09-18 06:21 UTC
The newest version of the PDF user guide (4 months old) seems to be empty/completely white despite it having 35MB in size. Opened with Chrome and Adobe Reader.
[UserGuide@Master](https://github.com/plotly/dash-docs/blob/master/pdf-docs/Dash_User_Guide_and_Documentation.pdf)

**Comment by alexcjohnson** [comment] 2020-09-18 15:34
duplicate of #897

**Closed by alexcjohnson** 2020-09-18 15:34 UTC
